server {
    listen 80;

    location /appuser/ {
        proxy_pass http://appuserservice:9200/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /applog/ {
        proxy_pass http://applogservice:9100/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth/ {
        proxy_pass http://notification-service:8300/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}